openapi: 3.0.1
info:
  title: createorderskd
  description: Azure Logic App.
  version: '1.0'
servers:
  - url: https://skd-apim-test.azure-api.net/createorderapi
paths:
  /manual/paths/invoke:
    post:
      summary: manual-invoke
      description: Trigger a run of the logic app.
      operationId: manual-invoke
      requestBody:
        description: The request body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-manual'
            example:
              customer_name: string
              order_date: string
              order_id: 0
              order_value: 0
      responses:
        '200':
          description: The Logic App Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManualPathsInvokePost200ApplicationJsonResponse'
components:
  schemas:
    request-manual:
      type: object
      properties:
        customer_name:
          type: string
        order_date:
          type: string
        order_id:
          type: integer
        order_value:
          type: number
    ManualPathsInvokePost200ApplicationJsonResponse:
      type: object
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]