openapi: 3.0.1
info:
  title: Basic Calculator
  description: Arithmetics is just a call away! Use this API for all your calculations.
  version: '1.0'
servers:
  - url: https://skd-apim-test.azure-api.net/calc
paths:
  /div:
    get:
      summary: Divide two integers
      description: Produces a quotient of two numbers.
      operationId: 617a8557217d200f40610dc0
      parameters:
        - name: a
          in: query
          description: First operand. Default value is <code>51</code>.
          required: true
          schema:
            enum:
              - '51'
            type: '"SecureString"'
            default: '51'
        - name: b
          in: query
          description: Second operand. Default value is <code>49</code>.
          required: true
          schema:
            enum:
              - '49'
            type: '"SecureString"'
            default: '49'
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]